graphMetadata:
  condensedEdgeTypeMap:
    '0':
      dstNodeType: paper
      relation: to
      srcNodeType: author
    '1':
      dstNodeType: author
      relation: to
      srcNodeType: paper
    '2':
      dstNodeType: paper
      relation: to
      srcNodeType: term
  condensedNodeTypeMap:
    '0': author
    '1': paper
    '2': term
  edgeTypes:
  - dstNodeType: paper
    relation: to
    srcNodeType: author
  - dstNodeType: author
    relation: to
    srcNodeType: paper
  - dstNodeType: paper
    relation: to
    srcNodeType: term
  nodeTypes:
  - author
  - paper
  - term
taskMetadata:
  nodeAnchorBasedLinkPredictionTaskMetadata:
    supervisionEdgeTypes:
    - dstNodeType: author
      relation: to
      srcNodeType: paper
datasetConfig:
  dataPreprocessorConfig:
    dataPreprocessorConfigClsPath: gigl.src.mocking.mocking_assets.passthrough_preprocessor_config_for_mocked_assets.PassthroughPreprocessorConfigForMockedAssets
    dataPreprocessorArgs:
      mocked_dataset_name: 'dblp_node_anchor_edge_features_lp'
  subgraphSamplerConfig:
    numPositiveSamples: 1
    subgraphSamplingStrategy:
      messagePassingPaths:
        paths:
        - rootNodeType: paper
          samplingOps:
          - edgeType:
              dstNodeType: paper
              relation: to
              srcNodeType: author
            opName: op_1
            randomUniform:
              numNodesToSample: 10
          - edgeType:
              dstNodeType: paper
              relation: to
              srcNodeType: term
            opName: op_2
            randomUniform:
              numNodesToSample: 10
          - edgeType:
              dstNodeType: author
              relation: to
              srcNodeType: paper
            opName: op_3
            inputOpNames:
            - op_1
            randomUniform:
              numNodesToSample: 10
        - rootNodeType: author
          samplingOps:
          - edgeType:
              dstNodeType: author
              relation: to
              srcNodeType: paper
            opName: op_4
            randomUniform:
              numNodesToSample: 10
          - edgeType:
              dstNodeType: paper
              relation: to
              srcNodeType: term
            opName: op_5
            inputOpNames:
            - op_4
            randomUniform:
              numNodesToSample: 10
          - edgeType:
              dstNodeType: paper
              relation: to
              srcNodeType: author
            opName: op_6
            inputOpNames:
            - op_4
            randomUniform:
              numNodesToSample: 10
    graphDbConfig:
      graph_db_args:
        use_local_sampler: 'true'
  splitGeneratorConfig:
    assignerArgs:
      seed: '42'
      test_split: '0.2'
      train_split: '0.7'
      val_split: '0.1'
    assignerClsPath: splitgenerator.lib.assigners.TransductiveEdgeToLinkSplitHashingAssigner
    splitStrategyClsPath: splitgenerator.lib.split_strategies.TransductiveNodeAnchorBasedLinkPredictionSplitStrategy
inferencerConfig:
  inferencerArgs:
    gnn_model_class_path: 'gigl.src.common.models.pyg.heterogeneous.HGT'
    early_stop_patience: '1'
    main_sample_batch_size: '16'
    num_test_batches: '8'
    num_val_batches: '8'
    random_negative_sample_batch_size: '16'
    random_negative_sample_batch_size_for_evaluation: '32'
    val_every_num_batches: '8'
    train_main_sample_num_workers: '1'
    train_random_sample_num_workers: '1'
    val_main_sample_num_workers: '1'
    val_random_sample_num_workers: '1'
    test_main_sample_num_workers: '1'
    test_random_sample_num_workers: '1'
  inferencerClsPath: gigl.src.common.modeling_task_specs.node_anchor_based_link_prediction_modeling_task_spec.NodeAnchorBasedLinkPredictionModelingTaskSpec
trainerConfig:
  trainerArgs:
    should_enable_find_unused_parameters: 'True'
    gnn_model_class_path: 'gigl.src.common.models.pyg.heterogeneous.HGT'
    early_stop_patience: '1'
    main_sample_batch_size: '16'
    num_test_batches: '8'
    num_val_batches: '8'
    random_negative_sample_batch_size: '16'
    random_negative_sample_batch_size_for_evaluation: '32'
    val_every_num_batches: '8'
    train_main_sample_num_workers: '1'
    train_random_sample_num_workers: '1'
    val_main_sample_num_workers: '1'
    val_random_sample_num_workers: '1'
    test_main_sample_num_workers: '1'
    test_random_sample_num_workers: '1'
  trainerClsPath: gigl.src.common.modeling_task_specs.node_anchor_based_link_prediction_modeling_task_spec.NodeAnchorBasedLinkPredictionModelingTaskSpec