graphMetadata:
  edgeTypes:
  - dstNodeType: paper
    relation: cites
    srcNodeType: paper
  nodeTypes:
  - paper
taskMetadata:
  nodeBasedTaskMetadata:
    supervisionNodeTypes:
      - paper
datasetConfig:
  dataPreprocessorConfig:
    dataPreprocessorConfigClsPath: gigl.src.mocking.mocking_assets.passthrough_preprocessor_config_for_mocked_assets.PassthroughPreprocessorConfigForMockedAssets
    dataPreprocessorArgs:
      # Supported keys in python/gigl/src/mocking/lib/mocked_dataset_artifact_metadata.json
      mocked_dataset_name: 'cora_homogeneous_supervised_node_classification_edge_features'
  splitGeneratorConfig:
    assignerArgs:
      seed: '42'
      test_split: '0.2'
      train_split: '0.7'
      val_split: '0.1'
    assignerClsPath: splitgenerator.lib.assigners.NodeToDatasetSplitHashingAssigner
    splitStrategyClsPath: splitgenerator.lib.split_strategies.TransductiveSupervisedNodeClassificationSplitStrategy
  subgraphSamplerConfig:
    numHops: 2
    numNeighborsToSample: 10
    numPositiveSamples: 1
inferencerConfig:
  inferencerArgs:
    batch_size: '16'
    num_epochs: '1'
    out_dim: '7'
  inferencerClsPath: gigl.src.common.modeling_task_specs.node_classification_modeling_task_spec.NodeClassificationModelingTaskSpec
trainerConfig:
  trainerArgs:
    batch_size: '16'
    num_epochs: '1'
    out_dim: '7'
  trainerClsPath: gigl.src.common.modeling_task_specs.node_classification_modeling_task_spec.NodeClassificationModelingTaskSpec

