# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapchat/research/gbml/inference_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/snapchat/research/gbml/inference_metadata.proto\x12\x16snapchat.research.gbml\"\x8a\x02\n\x11InferenceMetadata\x12\x81\x01\n\'node_type_to_inferencer_output_info_map\x18\x01 \x03(\x0b\x32P.snapchat.research.gbml.InferenceMetadata.NodeTypeToInferencerOutputInfoMapEntry\x1aq\n&NodeTypeToInferencerOutputInfoMapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.snapchat.research.gbml.InferenceOutput:\x02\x38\x01\"w\n\x0fInferenceOutput\x12\x1c\n\x0f\x65mbeddings_path\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x1d\n\x10predictions_path\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x12\n\x10_embeddings_pathB\x13\n\x11_predictions_pathb\x06proto3')



_INFERENCEMETADATA = DESCRIPTOR.message_types_by_name['InferenceMetadata']
_INFERENCEMETADATA_NODETYPETOINFERENCEROUTPUTINFOMAPENTRY = _INFERENCEMETADATA.nested_types_by_name['NodeTypeToInferencerOutputInfoMapEntry']
_INFERENCEOUTPUT = DESCRIPTOR.message_types_by_name['InferenceOutput']
InferenceMetadata = _reflection.GeneratedProtocolMessageType('InferenceMetadata', (_message.Message,), {

  'NodeTypeToInferencerOutputInfoMapEntry' : _reflection.GeneratedProtocolMessageType('NodeTypeToInferencerOutputInfoMapEntry', (_message.Message,), {
    'DESCRIPTOR' : _INFERENCEMETADATA_NODETYPETOINFERENCEROUTPUTINFOMAPENTRY,
    '__module__' : 'snapchat.research.gbml.inference_metadata_pb2'
    # @@protoc_insertion_point(class_scope:snapchat.research.gbml.InferenceMetadata.NodeTypeToInferencerOutputInfoMapEntry)
    })
  ,
  'DESCRIPTOR' : _INFERENCEMETADATA,
  '__module__' : 'snapchat.research.gbml.inference_metadata_pb2'
  # @@protoc_insertion_point(class_scope:snapchat.research.gbml.InferenceMetadata)
  })
_sym_db.RegisterMessage(InferenceMetadata)
_sym_db.RegisterMessage(InferenceMetadata.NodeTypeToInferencerOutputInfoMapEntry)

InferenceOutput = _reflection.GeneratedProtocolMessageType('InferenceOutput', (_message.Message,), {
  'DESCRIPTOR' : _INFERENCEOUTPUT,
  '__module__' : 'snapchat.research.gbml.inference_metadata_pb2'
  # @@protoc_insertion_point(class_scope:snapchat.research.gbml.InferenceOutput)
  })
_sym_db.RegisterMessage(InferenceOutput)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INFERENCEMETADATA_NODETYPETOINFERENCEROUTPUTINFOMAPENTRY._options = None
  _INFERENCEMETADATA_NODETYPETOINFERENCEROUTPUTINFOMAPENTRY._serialized_options = b'8\001'
  _INFERENCEMETADATA._serialized_start=76
  _INFERENCEMETADATA._serialized_end=342
  _INFERENCEMETADATA_NODETYPETOINFERENCEROUTPUTINFOMAPENTRY._serialized_start=229
  _INFERENCEMETADATA_NODETYPETOINFERENCEROUTPUTINFOMAPENTRY._serialized_end=342
  _INFERENCEOUTPUT._serialized_start=344
  _INFERENCEOUTPUT._serialized_end=463
# @@protoc_insertion_point(module_scope)
