"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class PostProcessedMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    POST_PROCESSOR_LOG_METRICS_URI_FIELD_NUMBER: builtins.int
    post_processor_log_metrics_uri: builtins.str
    """The path to the post processor evaluation results"""
    def __init__(
        self,
        *,
        post_processor_log_metrics_uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["post_processor_log_metrics_uri", b"post_processor_log_metrics_uri"]) -> None: ...

global___PostProcessedMetadata = PostProcessedMetadata
