# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: snapchat/research/gbml/trained_model_metadata.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n3snapchat/research/gbml/trained_model_metadata.proto\x12\x16snapchat.research.gbml\"\x85\x01\n\x14TrainedModelMetadata\x12\x19\n\x11trained_model_uri\x18\x01 \x01(\t\x12\x1a\n\x12scripted_model_uri\x18\x02 \x01(\t\x12\x18\n\x10\x65val_metrics_uri\x18\x03 \x01(\t\x12\x1c\n\x14tensorboard_logs_uri\x18\x04 \x01(\tb\x06proto3')



_TRAINEDMODELMETADATA = DESCRIPTOR.message_types_by_name['TrainedModelMetadata']
TrainedModelMetadata = _reflection.GeneratedProtocolMessageType('TrainedModelMetadata', (_message.Message,), {
  'DESCRIPTOR' : _TRAINEDMODELMETADATA,
  '__module__' : 'snapchat.research.gbml.trained_model_metadata_pb2'
  # @@protoc_insertion_point(class_scope:snapchat.research.gbml.TrainedModelMetadata)
  })
_sym_db.RegisterMessage(TrainedModelMetadata)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRAINEDMODELMETADATA._serialized_start=80
  _TRAINEDMODELMETADATA._serialized_end=213
# @@protoc_insertion_point(module_scope)
