"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class TrainedModelMetadata(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TRAINED_MODEL_URI_FIELD_NUMBER: builtins.int
    SCRIPTED_MODEL_URI_FIELD_NUMBER: builtins.int
    EVAL_METRICS_URI_FIELD_NUMBER: builtins.int
    TENSORBOARD_LOGS_URI_FIELD_NUMBER: builtins.int
    trained_model_uri: builtins.str
    """The path to a trained PyTorch model."""
    scripted_model_uri: builtins.str
    """The path to above model which is TorchScripted."""
    eval_metrics_uri: builtins.str
    """The path where evaluation metrics are stored"""
    tensorboard_logs_uri: builtins.str
    """Path where tensorboard logs will be stored"""
    def __init__(
        self,
        *,
        trained_model_uri: builtins.str = ...,
        scripted_model_uri: builtins.str = ...,
        eval_metrics_uri: builtins.str = ...,
        tensorboard_logs_uri: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["eval_metrics_uri", b"eval_metrics_uri", "scripted_model_uri", b"scripted_model_uri", "tensorboard_logs_uri", b"tensorboard_logs_uri", "trained_model_uri", b"trained_model_uri"]) -> None: ...

global___TrainedModelMetadata = TrainedModelMetadata
