// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package snapchat.research.gbml.training_samples_schema

@SerialVersionUID(0L)
final case class Label(
    labelType: _root_.scala.Predef.String = "",
    label: _root_.scala.Int = 0,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[Label] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = labelType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = label
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeInt32Size(2, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = labelType
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = label
        if (__v != 0) {
          _output__.writeInt32(2, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withLabelType(__v: _root_.scala.Predef.String): Label = copy(labelType = __v)
    def withLabel(__v: _root_.scala.Int): Label = copy(label = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = labelType
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = label
          if (__t != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(labelType)
        case 2 => _root_.scalapb.descriptors.PInt(label)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: snapchat.research.gbml.training_samples_schema.Label.type = snapchat.research.gbml.training_samples_schema.Label
    // @@protoc_insertion_point(GeneratedMessage[snapchat.research.gbml.Label])
}

object Label extends scalapb.GeneratedMessageCompanion[snapchat.research.gbml.training_samples_schema.Label] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[snapchat.research.gbml.training_samples_schema.Label] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): snapchat.research.gbml.training_samples_schema.Label = {
    var __labelType: _root_.scala.Predef.String = ""
    var __label: _root_.scala.Int = 0
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __labelType = _input__.readStringRequireUtf8()
        case 16 =>
          __label = _input__.readInt32()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    snapchat.research.gbml.training_samples_schema.Label(
        labelType = __labelType,
        label = __label,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[snapchat.research.gbml.training_samples_schema.Label] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      snapchat.research.gbml.training_samples_schema.Label(
        labelType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        label = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Int]).getOrElse(0)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TrainingSamplesSchemaProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TrainingSamplesSchemaProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = snapchat.research.gbml.training_samples_schema.Label(
    labelType = "",
    label = 0
  )
  implicit class LabelLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, snapchat.research.gbml.training_samples_schema.Label]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, snapchat.research.gbml.training_samples_schema.Label](_l) {
    def labelType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.labelType)((c_, f_) => c_.copy(labelType = f_))
    def label: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.label)((c_, f_) => c_.copy(label = f_))
  }
  final val LABEL_TYPE_FIELD_NUMBER = 1
  final val LABEL_FIELD_NUMBER = 2
  def of(
    labelType: _root_.scala.Predef.String,
    label: _root_.scala.Int
  ): _root_.snapchat.research.gbml.training_samples_schema.Label = _root_.snapchat.research.gbml.training_samples_schema.Label(
    labelType,
    label
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[snapchat.research.gbml.Label])
}
