// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package snapchat.research.gbml.training_samples_schema

object TrainingSamplesSchemaProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    snapchat.research.gbml.graph_schema.GraphSchemaProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      snapchat.research.gbml.training_samples_schema.Label,
      snapchat.research.gbml.training_samples_schema.RootedNodeNeighborhood,
      snapchat.research.gbml.training_samples_schema.SupervisedNodeClassificationSample,
      snapchat.research.gbml.training_samples_schema.NodeAnchorBasedLinkPredictionSample,
      snapchat.research.gbml.training_samples_schema.SupervisedLinkBasedTaskSample
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CjRzbmFwY2hhdC9yZXNlYXJjaC9nYm1sL3RyYWluaW5nX3NhbXBsZXNfc2NoZW1hLnByb3RvEhZzbmFwY2hhdC5yZXNlYXJja
  C5nYm1sGilzbmFwY2hhdC9yZXNlYXJjaC9nYm1sL2dyYXBoX3NjaGVtYS5wcm90byJYCgVMYWJlbBItCgpsYWJlbF90eXBlGAEgA
  SgJQg7iPwsSCWxhYmVsVHlwZVIJbGFiZWxUeXBlEiAKBWxhYmVsGAIgASgFQgriPwcSBWxhYmVsUgVsYWJlbCK4AQoWUm9vdGVkT
  m9kZU5laWdoYm9yaG9vZBJICglyb290X25vZGUYASABKAsyHC5zbmFwY2hhdC5yZXNlYXJjaC5nYm1sLk5vZGVCDeI/ChIIcm9vd
  E5vZGVSCHJvb3ROb2RlElQKDG5laWdoYm9yaG9vZBgCIAEoCzIdLnNuYXBjaGF0LnJlc2VhcmNoLmdibWwuR3JhcGhCEeI/DhIMb
  mVpZ2hib3Job29kUgxuZWlnaGJvcmhvb2QiogIKIlN1cGVydmlzZWROb2RlQ2xhc3NpZmljYXRpb25TYW1wbGUSSAoJcm9vdF9ub
  2RlGAEgASgLMhwuc25hcGNoYXQucmVzZWFyY2guZ2JtbC5Ob2RlQg3iPwoSCHJvb3ROb2RlUghyb290Tm9kZRJUCgxuZWlnaGJvc
  mhvb2QYAiABKAsyHS5zbmFwY2hhdC5yZXNlYXJjaC5nYm1sLkdyYXBoQhHiPw4SDG5laWdoYm9yaG9vZFIMbmVpZ2hib3Job29kE
  lwKEHJvb3Rfbm9kZV9sYWJlbHMYAyADKAsyHS5zbmFwY2hhdC5yZXNlYXJjaC5nYm1sLkxhYmVsQhPiPxASDnJvb3ROb2RlTGFiZ
  WxzUg5yb290Tm9kZUxhYmVscyKwAwojTm9kZUFuY2hvckJhc2VkTGlua1ByZWRpY3Rpb25TYW1wbGUSSAoJcm9vdF9ub2RlGAEgA
  SgLMhwuc25hcGNoYXQucmVzZWFyY2guZ2JtbC5Ob2RlQg3iPwoSCHJvb3ROb2RlUghyb290Tm9kZRJVCg5oYXJkX25lZ19lZGdlc
  xgCIAMoCzIcLnNuYXBjaGF0LnJlc2VhcmNoLmdibWwuRWRnZUIR4j8OEgxoYXJkTmVnRWRnZXNSDGhhcmROZWdFZGdlcxJICglwb
  3NfZWRnZXMYBCADKAsyHC5zbmFwY2hhdC5yZXNlYXJjaC5nYm1sLkVkZ2VCDeI/ChIIcG9zRWRnZXNSCHBvc0VkZ2VzEkgKCW5lZ
  19lZGdlcxgFIAMoCzIcLnNuYXBjaGF0LnJlc2VhcmNoLmdibWwuRWRnZUIN4j8KEghuZWdFZGdlc1IIbmVnRWRnZXMSVAoMbmVpZ
  2hib3Job29kGAMgASgLMh0uc25hcGNoYXQucmVzZWFyY2guZ2JtbC5HcmFwaEIR4j8OEgxuZWlnaGJvcmhvb2RSDG5laWdoYm9ya
  G9vZCKdAgodU3VwZXJ2aXNlZExpbmtCYXNlZFRhc2tTYW1wbGUSSAoJcm9vdF9lZGdlGAEgASgLMhwuc25hcGNoYXQucmVzZWFyY
  2guZ2JtbC5FZGdlQg3iPwoSCHJvb3RFZGdlUghyb290RWRnZRJUCgxuZWlnaGJvcmhvb2QYAiABKAsyHS5zbmFwY2hhdC5yZXNlY
  XJjaC5nYm1sLkdyYXBoQhHiPw4SDG5laWdoYm9yaG9vZFIMbmVpZ2hib3Job29kElwKEHJvb3RfZWRnZV9sYWJlbHMYAyADKAsyH
  S5zbmFwY2hhdC5yZXNlYXJjaC5nYm1sLkxhYmVsQhPiPxASDnJvb3RFZGdlTGFiZWxzUg5yb290RWRnZUxhYmVsc2IGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      snapchat.research.gbml.graph_schema.GraphSchemaProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}