// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package snapchat.research.gbml.gigl_resource_config

/** Configuration for Dataflow Components
  *
  * @param numWorkers
  *   Number of workers for Dataflow resources
  * @param maxNumWorkers
  *   Maximum number of workers for Dataflow resources
  * @param machineType
  *   Machine type for Dataflow resources
  * @param diskSizeGb
  *   Disk size in GB for Dataflow resources
  */
@SerialVersionUID(0L)
final case class DataflowResourceConfig(
    numWorkers: _root_.scala.Int = 0,
    maxNumWorkers: _root_.scala.Int = 0,
    machineType: _root_.scala.Predef.String = "",
    diskSizeGb: _root_.scala.Int = 0,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[DataflowResourceConfig] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = numWorkers
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(1, __value)
        }
      };
      
      {
        val __value = maxNumWorkers
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(2, __value)
        }
      };
      
      {
        val __value = machineType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = diskSizeGb
        if (__value != 0) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeUInt32Size(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = numWorkers
        if (__v != 0) {
          _output__.writeUInt32(1, __v)
        }
      };
      {
        val __v = maxNumWorkers
        if (__v != 0) {
          _output__.writeUInt32(2, __v)
        }
      };
      {
        val __v = machineType
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = diskSizeGb
        if (__v != 0) {
          _output__.writeUInt32(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withNumWorkers(__v: _root_.scala.Int): DataflowResourceConfig = copy(numWorkers = __v)
    def withMaxNumWorkers(__v: _root_.scala.Int): DataflowResourceConfig = copy(maxNumWorkers = __v)
    def withMachineType(__v: _root_.scala.Predef.String): DataflowResourceConfig = copy(machineType = __v)
    def withDiskSizeGb(__v: _root_.scala.Int): DataflowResourceConfig = copy(diskSizeGb = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = numWorkers
          if (__t != 0) __t else null
        }
        case 2 => {
          val __t = maxNumWorkers
          if (__t != 0) __t else null
        }
        case 3 => {
          val __t = machineType
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = diskSizeGb
          if (__t != 0) __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PInt(numWorkers)
        case 2 => _root_.scalapb.descriptors.PInt(maxNumWorkers)
        case 3 => _root_.scalapb.descriptors.PString(machineType)
        case 4 => _root_.scalapb.descriptors.PInt(diskSizeGb)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig.type = snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig
    // @@protoc_insertion_point(GeneratedMessage[snapchat.research.gbml.DataflowResourceConfig])
}

object DataflowResourceConfig extends scalapb.GeneratedMessageCompanion[snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig = {
    var __numWorkers: _root_.scala.Int = 0
    var __maxNumWorkers: _root_.scala.Int = 0
    var __machineType: _root_.scala.Predef.String = ""
    var __diskSizeGb: _root_.scala.Int = 0
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 8 =>
          __numWorkers = _input__.readUInt32()
        case 16 =>
          __maxNumWorkers = _input__.readUInt32()
        case 26 =>
          __machineType = _input__.readStringRequireUtf8()
        case 32 =>
          __diskSizeGb = _input__.readUInt32()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig(
        numWorkers = __numWorkers,
        maxNumWorkers = __maxNumWorkers,
        machineType = __machineType,
        diskSizeGb = __diskSizeGb,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig(
        numWorkers = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        maxNumWorkers = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Int]).getOrElse(0),
        machineType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        diskSizeGb = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Int]).getOrElse(0)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = GiglResourceConfigProto.javaDescriptor.getMessageTypes().get(1)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = GiglResourceConfigProto.scalaDescriptor.messages(1)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig(
    numWorkers = 0,
    maxNumWorkers = 0,
    machineType = "",
    diskSizeGb = 0
  )
  implicit class DataflowResourceConfigLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig](_l) {
    def numWorkers: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.numWorkers)((c_, f_) => c_.copy(numWorkers = f_))
    def maxNumWorkers: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.maxNumWorkers)((c_, f_) => c_.copy(maxNumWorkers = f_))
    def machineType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.machineType)((c_, f_) => c_.copy(machineType = f_))
    def diskSizeGb: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Int] = field(_.diskSizeGb)((c_, f_) => c_.copy(diskSizeGb = f_))
  }
  final val NUM_WORKERS_FIELD_NUMBER = 1
  final val MAX_NUM_WORKERS_FIELD_NUMBER = 2
  final val MACHINE_TYPE_FIELD_NUMBER = 3
  final val DISK_SIZE_GB_FIELD_NUMBER = 4
  def of(
    numWorkers: _root_.scala.Int,
    maxNumWorkers: _root_.scala.Int,
    machineType: _root_.scala.Predef.String,
    diskSizeGb: _root_.scala.Int
  ): _root_.snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig = _root_.snapchat.research.gbml.gigl_resource_config.DataflowResourceConfig(
    numWorkers,
    maxNumWorkers,
    machineType,
    diskSizeGb
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[snapchat.research.gbml.DataflowResourceConfig])
}
