# This file defines all constants for metrics used by GBML project

DELIMITER = "."

TIMER_S = "time_s"  # in seconds
PIPELINE_COMPONENT_PREFIX = "pipeline"
OFFLINE_METRIC_PREFIX = "offline_metric"

COMPONENT_CONFIG_POPULATOR_PREFIX = (
    f"{PIPELINE_COMPONENT_PREFIX}{DELIMITER}config_populator"
)
COMPONENT_PREPROCESSOR_PREFIX = f"{PIPELINE_COMPONENT_PREFIX}{DELIMITER}preprocessor"
COMPONENT_SPLIT_GENERATOR_PREFIX = (
    f"{PIPELINE_COMPONENT_PREFIX}{DELIMITER}split_generator"
)
COMPONENT_SUBGRAPH_SAMPLER_PREFIX = (
    f"{PIPELINE_COMPONENT_PREFIX}{DELIMITER}subgraph_sampler"
)
COMPONENT_TRAINER_PREFIX = f"{PIPELINE_COMPONENT_PREFIX}{DELIMITER}trainer"
COMPONENT_INFERENCER_PREFIX = f"{PIPELINE_COMPONENT_PREFIX}{DELIMITER}inferencer"
COMPONENT_POSTPROCESSOR_PREFIX = f"{PIPELINE_COMPONENT_PREFIX}{DELIMITER}post_processor"

# Total time cost for each kfp component
TIMER_CONFIG_POPULATOR_S = f"{COMPONENT_CONFIG_POPULATOR_PREFIX}{DELIMITER}{TIMER_S}"
TIMER_PREPROCESSOR_S = f"{COMPONENT_PREPROCESSOR_PREFIX}{DELIMITER}{TIMER_S}"
TIMER_SPLIT_GENERATOR_S = f"{COMPONENT_SPLIT_GENERATOR_PREFIX}{DELIMITER}{TIMER_S}"
TIMER_SUBGRAPH_SAMPLER_S = f"{COMPONENT_SUBGRAPH_SAMPLER_PREFIX}{DELIMITER}{TIMER_S}"
TIMER_TRAINER_S = f"{COMPONENT_TRAINER_PREFIX}{DELIMITER}{TIMER_S}"
TIMER_INFERENCER_S = f"{COMPONENT_INFERENCER_PREFIX}{DELIMITER}{TIMER_S}"
TIMER_POST_PROCESSOR_S = f"{COMPONENT_POSTPROCESSOR_PREFIX}{DELIMITER}{TIMER_S}"

# SUBGRAPH_SAMPLER
COUNT_SGS_USES_GRAPHDB = (
    f"{COMPONENT_SUBGRAPH_SAMPLER_PREFIX}{DELIMITER}sgs_uses_graphdb"
)

# TRAINER
TIMER_TRAINER_EXPORT_INFERENCE_ASSETS_S = (
    f"{COMPONENT_TRAINER_PREFIX}{DELIMITER}export_inference_assets{DELIMITER}{TIMER_S}"
)
TIMER_TRAINER_SETUP_ENV_S = (
    f"{COMPONENT_TRAINER_PREFIX}{DELIMITER}setup_env{DELIMITER}{TIMER_S}"
)
TIMER_TRAINER_CLEANUP_ENV_S = (
    f"{COMPONENT_TRAINER_PREFIX}{DELIMITER}cleanup_env{DELIMITER}{TIMER_S}"
)

# INFERENCER
