// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package snapchat.research.gbml.subgraph_sampling_strategy

@SerialVersionUID(0L)
final case class MessagePassingPath(
    rootNodeType: _root_.scala.Predef.String = "",
    samplingOps: _root_.scala.Seq[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp] = _root_.scala.Seq.empty,
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[MessagePassingPath] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = rootNodeType
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      samplingOps.foreach { __item =>
        val __value = __item
        __size += 1 + _root_.com.google.protobuf.CodedOutputStream.computeUInt32SizeNoTag(__value.serializedSize) + __value.serializedSize
      }
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = rootNodeType
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      samplingOps.foreach { __v =>
        val __m = __v
        _output__.writeTag(2, 2)
        _output__.writeUInt32NoTag(__m.serializedSize)
        __m.writeTo(_output__)
      };
      unknownFields.writeTo(_output__)
    }
    def withRootNodeType(__v: _root_.scala.Predef.String): MessagePassingPath = copy(rootNodeType = __v)
    def clearSamplingOps = copy(samplingOps = _root_.scala.Seq.empty)
    def addSamplingOps(__vs: snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp *): MessagePassingPath = addAllSamplingOps(__vs)
    def addAllSamplingOps(__vs: Iterable[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp]): MessagePassingPath = copy(samplingOps = samplingOps ++ __vs)
    def withSamplingOps(__v: _root_.scala.Seq[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp]): MessagePassingPath = copy(samplingOps = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = rootNodeType
          if (__t != "") __t else null
        }
        case 2 => samplingOps
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(rootNodeType)
        case 2 => _root_.scalapb.descriptors.PRepeated(samplingOps.iterator.map(_.toPMessage).toVector)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath.type = snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath
    // @@protoc_insertion_point(GeneratedMessage[snapchat.research.gbml.MessagePassingPath])
}

object MessagePassingPath extends scalapb.GeneratedMessageCompanion[snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath = {
    var __rootNodeType: _root_.scala.Predef.String = ""
    val __samplingOps: _root_.scala.collection.immutable.VectorBuilder[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp] = new _root_.scala.collection.immutable.VectorBuilder[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp]
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __rootNodeType = _input__.readStringRequireUtf8()
        case 18 =>
          __samplingOps += _root_.scalapb.LiteParser.readMessage[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp](_input__)
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath(
        rootNodeType = __rootNodeType,
        samplingOps = __samplingOps.result(),
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath(
        rootNodeType = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        samplingOps = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Seq[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp]]).getOrElse(_root_.scala.Seq.empty)
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = SubgraphSamplingStrategyProto.javaDescriptor.getMessageTypes().get(5)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = SubgraphSamplingStrategyProto.scalaDescriptor.messages(5)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = {
    var __out: _root_.scalapb.GeneratedMessageCompanion[_] = null
    (__number: @_root_.scala.unchecked) match {
      case 2 => __out = snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp
    }
    __out
  }
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath(
    rootNodeType = "",
    samplingOps = _root_.scala.Seq.empty
  )
  implicit class MessagePassingPathLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath](_l) {
    def rootNodeType: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.rootNodeType)((c_, f_) => c_.copy(rootNodeType = f_))
    def samplingOps: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Seq[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp]] = field(_.samplingOps)((c_, f_) => c_.copy(samplingOps = f_))
  }
  final val ROOT_NODE_TYPE_FIELD_NUMBER = 1
  final val SAMPLING_OPS_FIELD_NUMBER = 2
  def of(
    rootNodeType: _root_.scala.Predef.String,
    samplingOps: _root_.scala.Seq[snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp]
  ): _root_.snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath = _root_.snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath(
    rootNodeType,
    samplingOps
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[snapchat.research.gbml.MessagePassingPath])
}
