// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package snapchat.research.gbml.subgraph_sampling_strategy

object SubgraphSamplingStrategyProto extends _root_.scalapb.GeneratedFileObject {
  lazy val dependencies: Seq[_root_.scalapb.GeneratedFileObject] = Seq(
    snapchat.research.gbml.graph_schema.GraphSchemaProto
  )
  lazy val messagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] =
    Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]](
      snapchat.research.gbml.subgraph_sampling_strategy.RandomUniform,
      snapchat.research.gbml.subgraph_sampling_strategy.RandomWeighted,
      snapchat.research.gbml.subgraph_sampling_strategy.TopK,
      snapchat.research.gbml.subgraph_sampling_strategy.UserDefined,
      snapchat.research.gbml.subgraph_sampling_strategy.SamplingOp,
      snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPath,
      snapchat.research.gbml.subgraph_sampling_strategy.MessagePassingPathStrategy,
      snapchat.research.gbml.subgraph_sampling_strategy.GlobalRandomUniformStrategy,
      snapchat.research.gbml.subgraph_sampling_strategy.SubgraphSamplingStrategy
    )
  private lazy val ProtoBytes: _root_.scala.Array[Byte] =
      scalapb.Encoding.fromBase64(scala.collection.immutable.Seq(
  """CjdzbmFwY2hhdC9yZXNlYXJjaC9nYm1sL3N1YmdyYXBoX3NhbXBsaW5nX3N0cmF0ZWd5LnByb3RvEhZzbmFwY2hhdC5yZXNlY
  XJjaC5nYm1sGilzbmFwY2hhdC9yZXNlYXJjaC9nYm1sL2dyYXBoX3NjaGVtYS5wcm90byJVCg1SYW5kb21Vbmlmb3JtEkQKE251b
  V9ub2Rlc190b19zYW1wbGUYASABKAVCFeI/EhIQbnVtTm9kZXNUb1NhbXBsZVIQbnVtTm9kZXNUb1NhbXBsZSKPAQoOUmFuZG9tV
  2VpZ2h0ZWQSRAoTbnVtX25vZGVzX3RvX3NhbXBsZRgBIAEoBUIV4j8SEhBudW1Ob2Rlc1RvU2FtcGxlUhBudW1Ob2Rlc1RvU2Ftc
  GxlEjcKDmVkZ2VfZmVhdF9uYW1lGAIgASgJQhHiPw4SDGVkZ2VGZWF0TmFtZVIMZWRnZUZlYXROYW1lIoUBCgRUb3BLEkQKE251b
  V9ub2Rlc190b19zYW1wbGUYASABKAVCFeI/EhIQbnVtTm9kZXNUb1NhbXBsZVIQbnVtTm9kZXNUb1NhbXBsZRI3Cg5lZGdlX2ZlY
  XRfbmFtZRgCIAEoCUIR4j8OEgxlZGdlRmVhdE5hbWVSDGVkZ2VGZWF0TmFtZSLkAQoLVXNlckRlZmluZWQSLgoLcGF0aF90b191Z
  GYYASABKAlCDuI/CxIJcGF0aFRvVWRmUglwYXRoVG9VZGYSVAoGcGFyYW1zGAIgAygLMi8uc25hcGNoYXQucmVzZWFyY2guZ2Jtb
  C5Vc2VyRGVmaW5lZC5QYXJhbXNFbnRyeUIL4j8IEgZwYXJhbXNSBnBhcmFtcxpPCgtQYXJhbXNFbnRyeRIaCgNrZXkYASABKAlCC
  OI/BRIDa2V5UgNrZXkSIAoFdmFsdWUYAiABKAlCCuI/BxIFdmFsdWVSBXZhbHVlOgI4ASKnBQoKU2FtcGxpbmdPcBIkCgdvcF9uY
  W1lGAEgASgJQgviPwgSBm9wTmFtZVIGb3BOYW1lEkwKCWVkZ2VfdHlwZRgCIAEoCzIgLnNuYXBjaGF0LnJlc2VhcmNoLmdibWwuR
  WRnZVR5cGVCDeI/ChIIZWRnZVR5cGVSCGVkZ2VUeXBlEjcKDmlucHV0X29wX25hbWVzGAMgAygJQhHiPw4SDGlucHV0T3BOYW1lc
  1IMaW5wdXRPcE5hbWVzEmIKDnJhbmRvbV91bmlmb3JtGGQgASgLMiUuc25hcGNoYXQucmVzZWFyY2guZ2JtbC5SYW5kb21Vbmlmb
  3JtQhLiPw8SDXJhbmRvbVVuaWZvcm1IAFINcmFuZG9tVW5pZm9ybRJmCg9yYW5kb21fd2VpZ2h0ZWQYZSABKAsyJi5zbmFwY2hhd
  C5yZXNlYXJjaC5nYm1sLlJhbmRvbVdlaWdodGVkQhPiPxASDnJhbmRvbVdlaWdodGVkSABSDnJhbmRvbVdlaWdodGVkEj4KBXRvc
  F9rGGcgASgLMhwuc25hcGNoYXQucmVzZWFyY2guZ2JtbC5Ub3BLQgniPwYSBHRvcEtIAFIEdG9wSxJaCgx1c2VyX2RlZmluZWQYa
  CABKAsyIy5zbmFwY2hhdC5yZXNlYXJjaC5nYm1sLlVzZXJEZWZpbmVkQhDiPw0SC3VzZXJEZWZpbmVkSABSC3VzZXJEZWZpbmVkE
  nEKEnNhbXBsaW5nX2RpcmVjdGlvbhjIASABKA4yKS5zbmFwY2hhdC5yZXNlYXJjaC5nYm1sLlNhbXBsaW5nRGlyZWN0aW9uQhbiP
  xMSEXNhbXBsaW5nRGlyZWN0aW9uUhFzYW1wbGluZ0RpcmVjdGlvbkIRCg9zYW1wbGluZ19tZXRob2QipgEKEk1lc3NhZ2VQYXNza
  W5nUGF0aBI3Cg5yb290X25vZGVfdHlwZRgBIAEoCUIR4j8OEgxyb290Tm9kZVR5cGVSDHJvb3ROb2RlVHlwZRJXCgxzYW1wbGluZ
  19vcHMYAiADKAsyIi5zbmFwY2hhdC5yZXNlYXJjaC5nYm1sLlNhbXBsaW5nT3BCEOI/DRILc2FtcGxpbmdPcHNSC3NhbXBsaW5nT
  3BzImoKGk1lc3NhZ2VQYXNzaW5nUGF0aFN0cmF0ZWd5EkwKBXBhdGhzGAEgAygLMiouc25hcGNoYXQucmVzZWFyY2guZ2JtbC5NZ
  XNzYWdlUGFzc2luZ1BhdGhCCuI/BxIFcGF0aHNSBXBhdGhzIrUBChtHbG9iYWxSYW5kb21Vbmlmb3JtU3RyYXRlZ3kSJwoIbnVtX
  2hvcHMYASABKA1CDOI/CRIHbnVtSG9wc1IHbnVtSG9wcxJtChNyYW5kb21fdW5pZm9ybV9zcGVjGAIgASgLMiUuc25hcGNoYXQuc
  mVzZWFyY2guZ2JtbC5SYW5kb21Vbmlmb3JtQhbiPxMSEXJhbmRvbVVuaWZvcm1TcGVjUhFyYW5kb21Vbmlmb3JtU3BlYyKxAgoYU
  3ViZ3JhcGhTYW1wbGluZ1N0cmF0ZWd5EoIBChVtZXNzYWdlX3Bhc3NpbmdfcGF0aHMYASABKAsyMi5zbmFwY2hhdC5yZXNlYXJja
  C5nYm1sLk1lc3NhZ2VQYXNzaW5nUGF0aFN0cmF0ZWd5QhjiPxUSE21lc3NhZ2VQYXNzaW5nUGF0aHNIAFITbWVzc2FnZVBhc3Npb
  mdQYXRocxKDAQoVZ2xvYmFsX3JhbmRvbV91bmlmb3JtGAIgASgLMjMuc25hcGNoYXQucmVzZWFyY2guZ2JtbC5HbG9iYWxSYW5kb
  21Vbmlmb3JtU3RyYXRlZ3lCGOI/FRITZ2xvYmFsUmFuZG9tVW5pZm9ybUgAUhNnbG9iYWxSYW5kb21Vbmlmb3JtQgoKCHN0cmF0Z
  Wd5Kk0KEVNhbXBsaW5nRGlyZWN0aW9uEhsKCElOQ09NSU5HEAAaDeI/ChIISU5DT01JTkcSGwoIT1VUR09JTkcQARoN4j8KEghPV
  VRHT0lOR2IGcHJvdG8z"""
      ).mkString)
  lazy val scalaDescriptor: _root_.scalapb.descriptors.FileDescriptor = {
    val scalaProto = com.google.protobuf.descriptor.FileDescriptorProto.parseFrom(ProtoBytes)
    _root_.scalapb.descriptors.FileDescriptor.buildFrom(scalaProto, dependencies.map(_.scalaDescriptor))
  }
  lazy val javaDescriptor: com.google.protobuf.Descriptors.FileDescriptor = {
    val javaProto = com.google.protobuf.DescriptorProtos.FileDescriptorProto.parseFrom(ProtoBytes)
    com.google.protobuf.Descriptors.FileDescriptor.buildFrom(javaProto, _root_.scala.Array(
      snapchat.research.gbml.graph_schema.GraphSchemaProto.javaDescriptor
    ))
  }
  @deprecated("Use javaDescriptor instead. In a future version this will refer to scalaDescriptor.", "ScalaPB 0.5.47")
  def descriptor: com.google.protobuf.Descriptors.FileDescriptor = javaDescriptor
}