// Generated by the Scala Plugin for the Protocol Buffer Compiler.
// Do not edit!
//
// Protofile syntax: PROTO3

package snapchat.research.gbml.trained_model_metadata

/** @param trainedModelUri
  *   The path to a trained PyTorch model.
  * @param scriptedModelUri
  *   The path to above model which is TorchScripted.
  * @param evalMetricsUri
  *   The path where evaluation metrics are stored
  * @param tensorboardLogsUri
  *   Path where tensorboard logs will be stored
  */
@SerialVersionUID(0L)
final case class TrainedModelMetadata(
    trainedModelUri: _root_.scala.Predef.String = "",
    scriptedModelUri: _root_.scala.Predef.String = "",
    evalMetricsUri: _root_.scala.Predef.String = "",
    tensorboardLogsUri: _root_.scala.Predef.String = "",
    unknownFields: _root_.scalapb.UnknownFieldSet = _root_.scalapb.UnknownFieldSet.empty
    ) extends scalapb.GeneratedMessage with scalapb.lenses.Updatable[TrainedModelMetadata] {
    @transient
    private[this] var __serializedSizeMemoized: _root_.scala.Int = 0
    private[this] def __computeSerializedSize(): _root_.scala.Int = {
      var __size = 0
      
      {
        val __value = trainedModelUri
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(1, __value)
        }
      };
      
      {
        val __value = scriptedModelUri
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(2, __value)
        }
      };
      
      {
        val __value = evalMetricsUri
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(3, __value)
        }
      };
      
      {
        val __value = tensorboardLogsUri
        if (!__value.isEmpty) {
          __size += _root_.com.google.protobuf.CodedOutputStream.computeStringSize(4, __value)
        }
      };
      __size += unknownFields.serializedSize
      __size
    }
    override def serializedSize: _root_.scala.Int = {
      var __size = __serializedSizeMemoized
      if (__size == 0) {
        __size = __computeSerializedSize() + 1
        __serializedSizeMemoized = __size
      }
      __size - 1
      
    }
    def writeTo(`_output__`: _root_.com.google.protobuf.CodedOutputStream): _root_.scala.Unit = {
      {
        val __v = trainedModelUri
        if (!__v.isEmpty) {
          _output__.writeString(1, __v)
        }
      };
      {
        val __v = scriptedModelUri
        if (!__v.isEmpty) {
          _output__.writeString(2, __v)
        }
      };
      {
        val __v = evalMetricsUri
        if (!__v.isEmpty) {
          _output__.writeString(3, __v)
        }
      };
      {
        val __v = tensorboardLogsUri
        if (!__v.isEmpty) {
          _output__.writeString(4, __v)
        }
      };
      unknownFields.writeTo(_output__)
    }
    def withTrainedModelUri(__v: _root_.scala.Predef.String): TrainedModelMetadata = copy(trainedModelUri = __v)
    def withScriptedModelUri(__v: _root_.scala.Predef.String): TrainedModelMetadata = copy(scriptedModelUri = __v)
    def withEvalMetricsUri(__v: _root_.scala.Predef.String): TrainedModelMetadata = copy(evalMetricsUri = __v)
    def withTensorboardLogsUri(__v: _root_.scala.Predef.String): TrainedModelMetadata = copy(tensorboardLogsUri = __v)
    def withUnknownFields(__v: _root_.scalapb.UnknownFieldSet) = copy(unknownFields = __v)
    def discardUnknownFields = copy(unknownFields = _root_.scalapb.UnknownFieldSet.empty)
    def getFieldByNumber(__fieldNumber: _root_.scala.Int): _root_.scala.Any = {
      (__fieldNumber: @_root_.scala.unchecked) match {
        case 1 => {
          val __t = trainedModelUri
          if (__t != "") __t else null
        }
        case 2 => {
          val __t = scriptedModelUri
          if (__t != "") __t else null
        }
        case 3 => {
          val __t = evalMetricsUri
          if (__t != "") __t else null
        }
        case 4 => {
          val __t = tensorboardLogsUri
          if (__t != "") __t else null
        }
      }
    }
    def getField(__field: _root_.scalapb.descriptors.FieldDescriptor): _root_.scalapb.descriptors.PValue = {
      _root_.scala.Predef.require(__field.containingMessage eq companion.scalaDescriptor)
      (__field.number: @_root_.scala.unchecked) match {
        case 1 => _root_.scalapb.descriptors.PString(trainedModelUri)
        case 2 => _root_.scalapb.descriptors.PString(scriptedModelUri)
        case 3 => _root_.scalapb.descriptors.PString(evalMetricsUri)
        case 4 => _root_.scalapb.descriptors.PString(tensorboardLogsUri)
      }
    }
    def toProtoString: _root_.scala.Predef.String = _root_.scalapb.TextFormat.printToUnicodeString(this)
    def companion: snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata.type = snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata
    // @@protoc_insertion_point(GeneratedMessage[snapchat.research.gbml.TrainedModelMetadata])
}

object TrainedModelMetadata extends scalapb.GeneratedMessageCompanion[snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata] {
  implicit def messageCompanion: scalapb.GeneratedMessageCompanion[snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata] = this
  def parseFrom(`_input__`: _root_.com.google.protobuf.CodedInputStream): snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata = {
    var __trainedModelUri: _root_.scala.Predef.String = ""
    var __scriptedModelUri: _root_.scala.Predef.String = ""
    var __evalMetricsUri: _root_.scala.Predef.String = ""
    var __tensorboardLogsUri: _root_.scala.Predef.String = ""
    var `_unknownFields__`: _root_.scalapb.UnknownFieldSet.Builder = null
    var _done__ = false
    while (!_done__) {
      val _tag__ = _input__.readTag()
      _tag__ match {
        case 0 => _done__ = true
        case 10 =>
          __trainedModelUri = _input__.readStringRequireUtf8()
        case 18 =>
          __scriptedModelUri = _input__.readStringRequireUtf8()
        case 26 =>
          __evalMetricsUri = _input__.readStringRequireUtf8()
        case 34 =>
          __tensorboardLogsUri = _input__.readStringRequireUtf8()
        case tag =>
          if (_unknownFields__ == null) {
            _unknownFields__ = new _root_.scalapb.UnknownFieldSet.Builder()
          }
          _unknownFields__.parseField(tag, _input__)
      }
    }
    snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata(
        trainedModelUri = __trainedModelUri,
        scriptedModelUri = __scriptedModelUri,
        evalMetricsUri = __evalMetricsUri,
        tensorboardLogsUri = __tensorboardLogsUri,
        unknownFields = if (_unknownFields__ == null) _root_.scalapb.UnknownFieldSet.empty else _unknownFields__.result()
    )
  }
  implicit def messageReads: _root_.scalapb.descriptors.Reads[snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata] = _root_.scalapb.descriptors.Reads{
    case _root_.scalapb.descriptors.PMessage(__fieldsMap) =>
      _root_.scala.Predef.require(__fieldsMap.keys.forall(_.containingMessage eq scalaDescriptor), "FieldDescriptor does not match message type.")
      snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata(
        trainedModelUri = __fieldsMap.get(scalaDescriptor.findFieldByNumber(1).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        scriptedModelUri = __fieldsMap.get(scalaDescriptor.findFieldByNumber(2).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        evalMetricsUri = __fieldsMap.get(scalaDescriptor.findFieldByNumber(3).get).map(_.as[_root_.scala.Predef.String]).getOrElse(""),
        tensorboardLogsUri = __fieldsMap.get(scalaDescriptor.findFieldByNumber(4).get).map(_.as[_root_.scala.Predef.String]).getOrElse("")
      )
    case _ => throw new RuntimeException("Expected PMessage")
  }
  def javaDescriptor: _root_.com.google.protobuf.Descriptors.Descriptor = TrainedModelMetadataProto.javaDescriptor.getMessageTypes().get(0)
  def scalaDescriptor: _root_.scalapb.descriptors.Descriptor = TrainedModelMetadataProto.scalaDescriptor.messages(0)
  def messageCompanionForFieldNumber(__number: _root_.scala.Int): _root_.scalapb.GeneratedMessageCompanion[_] = throw new MatchError(__number)
  lazy val nestedMessagesCompanions: Seq[_root_.scalapb.GeneratedMessageCompanion[_ <: _root_.scalapb.GeneratedMessage]] = Seq.empty
  def enumCompanionForFieldNumber(__fieldNumber: _root_.scala.Int): _root_.scalapb.GeneratedEnumCompanion[_] = throw new MatchError(__fieldNumber)
  lazy val defaultInstance = snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata(
    trainedModelUri = "",
    scriptedModelUri = "",
    evalMetricsUri = "",
    tensorboardLogsUri = ""
  )
  implicit class TrainedModelMetadataLens[UpperPB](_l: _root_.scalapb.lenses.Lens[UpperPB, snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata]) extends _root_.scalapb.lenses.ObjectLens[UpperPB, snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata](_l) {
    def trainedModelUri: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.trainedModelUri)((c_, f_) => c_.copy(trainedModelUri = f_))
    def scriptedModelUri: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.scriptedModelUri)((c_, f_) => c_.copy(scriptedModelUri = f_))
    def evalMetricsUri: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.evalMetricsUri)((c_, f_) => c_.copy(evalMetricsUri = f_))
    def tensorboardLogsUri: _root_.scalapb.lenses.Lens[UpperPB, _root_.scala.Predef.String] = field(_.tensorboardLogsUri)((c_, f_) => c_.copy(tensorboardLogsUri = f_))
  }
  final val TRAINED_MODEL_URI_FIELD_NUMBER = 1
  final val SCRIPTED_MODEL_URI_FIELD_NUMBER = 2
  final val EVAL_METRICS_URI_FIELD_NUMBER = 3
  final val TENSORBOARD_LOGS_URI_FIELD_NUMBER = 4
  def of(
    trainedModelUri: _root_.scala.Predef.String,
    scriptedModelUri: _root_.scala.Predef.String,
    evalMetricsUri: _root_.scala.Predef.String,
    tensorboardLogsUri: _root_.scala.Predef.String
  ): _root_.snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata = _root_.snapchat.research.gbml.trained_model_metadata.TrainedModelMetadata(
    trainedModelUri,
    scriptedModelUri,
    evalMetricsUri,
    tensorboardLogsUri
  )
  // @@protoc_insertion_point(GeneratedMessageCompanion[snapchat.research.gbml.TrainedModelMetadata])
}
