name: 'Run Command on a Specified PR'
description: 'Runs a command and posts comments on a PR based on workflow progress'
inputs:
  pr_number:
    description: 'The pull request number'
    required: true
  command:
    description: 'The command to execute on the PR'
    required: true
  should_leave_progress_comments:
    description: 'Whether to leave comments to track the progress of the workflow'
    required: false
    default: 'false'
  descriptive_workflow_name:
    description: 'A descriptive name for the workflow used for tracking in comments'
    required: false
    default: 'Workflow'
runs:
  using: "composite"
  steps:
    - uses: snap-research/gigl/.github/actions/assert-is-collaborator@main
      id: assert_collaborator_ran_workflow
      with:
        username: ${{ github.triggering_actor }}
        initiating-pr-number: ${{ github.event.issue.number }}

    - name: Set up workflow URL
      shell: bash
      run: echo "WORKFLOW_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

    - name: Commment workflow started
      if: ${{ inputs.should_leave_progress_comments == 'true' }}
      uses: 'snap-research/gigl/.github/actions/comment-on-pr@main'
      with:
        pr_number: ${{ inputs.pr_number }}
        message: |
          # GiGL Automation
          🔄 `${{ inputs.descriptive_workflow_name }}` [started](${{ env.WORKFLOW_URL }}).

    - name: Checkout branch
      uses: snap-research/gigl/.github/actions/checkout-pr-branch@main
      with:
        pr_number: ${{ inputs.pr_number }}

    - name: Run specified command on the PR branch
      shell: bash
      run: ${{ inputs.command }}

    - name: Commment workflow succeeded
      if: ${{ inputs.should_leave_progress_comments == 'true' }}
      uses: 'snap-research/gigl/.github/actions/comment-on-pr@main'
      with:
        pr_number: ${{ inputs.pr_number }}
        message: |
          # GiGL Automation
          ✅ `${{ inputs.descriptive_workflow_name }}` [completed successfully](${{ env.WORKFLOW_URL }})!"

    # Failure handling step
    - name: Comment workflow failed
      # If assert_collaborator_ran_workflow step failed we can skip commenting, as that is handled already in the assertion step
      if: ${{ inputs.should_leave_progress_comments == 'true' && failure() && steps.assert_collaborator_ran_workflow.outcome != 'failure' }}
      uses: 'snap-research/gigl/.github/actions/comment-on-pr@main'
      with:
        pr_number: ${{ inputs.pr_number }}
        message: |
          # GiGL Automation
          ❌ `${{ inputs.descriptive_workflow_name }}` [failed](${{ env.WORKFLOW_URL }}).
          Please check the logs for more details.


