name: "Commit and Push Changes"
description: "Commits and pushes changes with a customizable commit message"
inputs:
  commit_message:
    description: "Commit message for the changes"
    required: true
    default: "Updated files via GitHub Actions"
runs:
  using: "composite"
  steps:
    - name: Commit and push changes
      env:
        COMMIT_MESSAGE: ${{ inputs.commit_message }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        
        # Check if there are any changes
        if git diff --cached --exit-code; then
          echo "No changes to commit."
          exit 0
        fi
        
        git commit -m "$COMMIT_MESSAGE"
        git push
      shell: bash