name: build-base-docker-images

on: [push]
# on:
#   issue_comment:
#     types: [created]

jobs:
  build-docker-images:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    # if: ${{ github.event.issue.pull_request }} && contains(github.event.comment.body, '/build_base_docker_images')

    steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Google Cloud Auth
          uses: 'google-github-actions/auth@v2'
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}
            workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
            service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

        - name: Set Up Cloud SDK
          uses: google-github-actions/setup-gcloud@v2
          with:
            project_id: ${{ secrets.GCP_PROJECT_ID }}

        - name: Build and Push Docker Images
          run: |
            TAG=${GITHUB_SHA::6}.${{github.run_number}}.${{github.run_attempt}}
            gcloud auth configure-docker us-central1-docker.pkg.dev
            GIGL_BASE_CUDA_IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gigl-base-images/gigl-cuda-base:${TAG}
            GIGL_BASE_CPU_IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gigl-base-images/gigl-cpu-base:${TAG}
            GIGL_BASE_DATAFLOW_IMAGE=us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/gigl-base-images/gigl-dataflow-base:${TAG}
            docker build -f ./containers/Dockerfile.cuda.base -t ${GIGL_BASE_CUDA_IMAGE} .
            echo "Pushed CUDA base image to ${GIGL_BASE_CUDA_IMAGE}"
            docker build -f ./containers/Dockerfile.cpu.base -t ${GIGL_BASE_CPU_IMAGE} .
            docker push ${GIGL_BASE_CPU_IMAGE}
            echo "Pushed CPU base image to ${GIGL_BASE_CPU_IMAGE}"
            echo "Will use CPU image ${GIGL_BASE_CPU_IMAGE} as base image for Dataflow image."
            docker build -f ./containers/Dockerfile.dataflow.base --build-arg BASE_IMAGE=${GIGL_BASE_CPU_IMAGE} -t ${GIGL_BASE_DATAFLOW_IMAGE} .
            docker push ${GIGL_BASE_DATAFLOW_IMAGE}
            echo "Pushed Dataflow base image to ${GIGL_BASE_DATAFLOW_IMAGE}"
