name: pr-comment-workflow

on:
  issue_comment:
    types: [created]

jobs:
  unit-test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/unit_test') }} 
    runs-on: ubuntu-latest
    steps:
    - name: Run Unit Tests
      uses: snap-research/gigl/.github/actions/run-command-on-pr@main
      with:
        pr_number: ${{ github.event.issue.number }}
        should_leave_progress_comments: "true"
        command: |
          make unit_test
  integration-test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/integration_test') }} 
    runs-on: ubuntu-latest
    steps:
    - name: Run Integration Tests
      uses: snap-research/gigl/.github/actions/run-command-on-pr@main
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      with:
          pr_number: ${{ github.event.issue.number }}
          should_leave_progress_comments: "true"
          command: |
              GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT make integration_test
  integration-e2e-test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/integration_end2end_test') }} 
    runs-on: ubuntu-latest
    steps:
    - name: Run Integration Tests
      uses: snap-research/gigl/.github/actions/run-command-on-pr@main
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      with:
          pr_number: ${{ github.event.issue.number }}
          should_leave_progress_comments: "true"
          command: |
            GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT make run_all_e2e_tests