name: generate-hashed-requirements

# This GitHub Action is triggered when a new comment is created on an issue.
on:
  issue_comment:
    types: [created]

jobs:
  setup-python-and-tools:
    # This job sets up Python and pip-tools on both Linux and macOS.
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14]
    steps:
      # Step 1: Check out the repository code.
      - uses: actions/checkout@v3

      # Step 2: Set up Python environment (Python 3.9.18).
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.18'

      # Step 3: Install pip-tools, which is used to generate hashed requirements.
      - name: Install pip-tools
        run: pip install pip-tools

  generate-linux-cpu-hashed-requirements:
    # This job runs on an Ubuntu-based runner.
    runs-on: ubuntu-latest
    needs: setup-python-and-tools  # Ensures Python setup is completed first
    
    if: contains(github.event.comment.body, '/generate_hashed_requirements')
    
    steps:
      # Step 4: Generate a hashed requirements file from pyproject.toml using pip-compile.
      - name: Generate hashed requirements for Linux Platform
        run: |
          pip-compile -v --allow-unsafe --generate-hashes --no-emit-index-url --resolver=backtracking \
          --output-file=requirements/linux_cpu_requirements_unified.txt \
          --extra torch25-cpu --extra transform \
          ./python/pyproject.toml

      # Step 5: Upload the generated hashed requirements file as an artifact.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux_cpu_requirements_unified
          path: requirements/linux_cpu_requirements_unified.txt

  generate-dev-linux-cpu-hashed-requirements:
    # This job runs on an Ubuntu-based runner.
    runs-on: ubuntu-latest
    needs: setup-python-and-tools  # Ensures Python setup is completed first
    
    steps:
      # Step 4: Generate a different hashed requirements file.
      - name: Generate dev hashed requirements for Linux CPU platform
        run: |
          pip-compile -v --allow-unsafe --generate-hashes --no-emit-index-url --resolver=backtracking \
          --output-file=requirements/dev_linux_cpu_requirements_unified.txt \
          --extra torch25-cpu --extra transform --extra dev \
          ./python/pyproject.toml

      # Step 5: Upload the new hashed requirements file as an artifact.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dev_linux_cpu_requirements_unified
          path: requirements/dev_linux_cpu_requirements_unified.txt

  generate-mac-hashed-requirements:
    # This job runs on a macOS-based runner (macOS 14) - Arm64 (Apple Silicon) runner.
    runs-on: macos-14
    needs: setup-python-and-tools  # Ensures Python setup is completed first
    
    if: contains(github.event.comment.body, '/generate_hashed_requirements')
    
    steps:
      # Step 4: Generate a hashed requirements file from pyproject.toml using pip-compile.
      - name: Generate hashed requirements for MAC
        run: |
          pip-compile -v --allow-unsafe --generate-hashes --no-emit-index-url --resolver=backtracking \
          --output-file=requirements/darwin_arm64_requirements_unified.txt \
          --extra torch25-cpu --extra transform \
          ./python/pyproject.toml

      # Step 5: Upload the generated hashed requirements file as an artifact.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: darwin_arm64_requirements_unified
          path: requirements/darwin_arm64_requirements_unified.txt
