name: generate-hashed-reqs

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR to run the workflow on'
        required: true

env:
  WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}


jobs:
  comment-workflow-started:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on PR
      uses: snap-research/gigl/.github/actions/comment-on-pr@main
      with:
        pr_number: ${{ inputs.pr_number }}
        message: |
          Starting to [generate](${{env.WORKFLOW_URL}}) hashed requirements from `pyproject.toml`.
          This may take a while, please be patient.
          Once done, the workflow will update the relevant `requirements/*.txt` files.

  compute-linux-hashed-requirements:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository code.
      - uses: actions/checkout@v4
      # Step 2: Check out the repository code and set up the Python environment.
      - uses: snap-research/gigl/.github/actions/setup-python-tools@main 
      # Step 3: Generate a hashed requirements file from pyproject.toml using pip-compile.
      - name: Generate all hashed requirements for Linux Platform
        uses: snap-research/gigl/.github/actions/run-command-on-pr@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          should_leave_progress_comments: "false"
          command: |
            make -j4 generate_dev_linux_cuda_hashed_requirements \
              generate_linux_cuda_hashed_requirements \
              generate_dev_linux_cpu_hashed_requirements \
              generate_linux_cpu_hashed_requirements
      # Step 4: Upload the computed hashed requirements file as an artifact.
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux_requirements
          path: |
            requirements/linux_cuda_requirements_unified.txt
            requirements/dev_linux_cuda_requirements_unified.txt
            requirements/linux_cpu_requirements_unified.txt
            requirements/dev_linux_cpu_requirements_unified.txt

  compute-mac-hashed-requirements:
    runs-on: macos-14 # macOS-based runner (macOS 14) - Arm64 (Apple Silicon) runner.
    steps:
      - uses: actions/checkout@v4
      - uses: snap-research/gigl/.github/actions/setup-python-tools@main 
      - name: Generate hashed requirements for MACOS (Silicon) platform
        uses: snap-research/gigl/.github/actions/run-command-on-pr@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
          should_leave_progress_comments: "false"
          command: |
            make -j2 generate_mac_arm64_cpu_hashed_requirements \
              generate_dev_mac_arm64_cpu_hashed_requirements
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac_requirements
          path: |
            requirements/darwin_arm64_requirements_unified.txt
            requirements/dev_darwin_arm64_requirements_unified.txt

  commit-hashed-requirements:
    needs: 
      - compute-linux-hashed-requirements
      - compute-mac-hashed-requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: snap-research/gigl/.github/actions/checkout-pr-branch@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          pr_number: ${{ inputs.pr_number }}
      - name: Download generated linux requirements artifacts
        uses: actions/download-artifact@v4
        with:
          name: linux_requirements
          path: requirements/
      - name: Download generated mac requirements artifacts
        uses: actions/download-artifact@v4
        with:
          name: mac_requirements
          path: requirements/
      - name: Commit and Push Hashed Requirement updates
        uses: snap-research/gigl/.github/actions/commit-and-push@main
        with:
          commit_message: "[AUTOMATED] Update all hashed requirements files"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: snap-research/gigl/.github/actions/comment-on-pr@main
        with:
          pr_number: ${{ inputs.pr_number }}
          message: |
            Built and pushed updated requirements files.
