name: On Demand Pr Comment Workflows

on:
  issue_comment:
    types: [created]

permissions:
  # Needed for gcloud auth: https://github.com/google-github-actions/auth
  id-token: 'write'
  contents: 'read'
  # Needed for commenting on PRs
  pull-requests: 'write'
  issues: 'write'

jobs:
  unit-test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/unit_test') }} 
    runs-on: ubuntu-latest
    steps:
    - name: Run Unit Tests
      uses: snap-research/gigl/.github/actions/run-command-on-pr@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        should_leave_progress_comments: "true"
        descriptive_workflow_name: "Unit Test"
        install_dev_deps: "true"
        setup_gcloud: "true"
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        gcp_service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        command: |
          make unit_test
  integration-test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/integration_test') }} 
    runs-on: ubuntu-latest
    steps:
    - name: Run Integration Tests
      uses: snap-research/gigl/.github/actions/run-command-on-pr@main
      env:
        GOOGLE_CLOUD_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        should_leave_progress_comments: "true"
        descriptive_workflow_name: "Integration Test"
        install_dev_deps: "true"
        setup_gcloud: "true"
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        gcp_service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        command: |
            GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT make integration_test
  integration-e2e-test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/integration_end2end_test') }} 
    runs-on: ubuntu-latest
    steps:
    - name: Run Integration Tests
      uses: snap-research/gigl/.github/actions/run-command-on-pr@main
      env:
        GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        should_leave_progress_comments: "true"
        descriptive_workflow_name: "Integration Test"
        install_dev_deps: "true"
        setup_gcloud: "true"
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        gcp_service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        command: |
          GOOGLE_CLOUD_PROJECT=$GOOGLE_CLOUD_PROJECT make run_all_e2e_tests
  test:
    if: ${{ github.event.issue.pull_request && contains(github.event.comment.body, '/info') }} 
    runs-on: ubuntu-latest
    steps:
    - name: Run Tests
      uses: snap-research/gigl/.github/actions/run-command-on-pr@main
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        pr_number: ${{ github.event.issue.number }}
        should_leave_progress_comments: "true"
        descriptive_workflow_name: "Info Test"
        install_dev_deps: "true"
        setup_gcloud: "true"
        gcp_project_id: ${{ secrets.GCP_PROJECT_ID }}
        workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
        gcp_service_account_email: ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}
        command: |
          gcloud info