name: build-base-docker-images

on: ["push"]

env:
  # Setting an environment variable with the value of a configuration variable
  owners: ${{ vars.OWNERS }}

jobs:
  unit-test:
    
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v3
        - name: Debug
          run: |
            echo "$owners"

